Almost_everything_MKII
LILKRASH/monsters-developers-project pull request #12
Opened 2023-11-27 02:24 UTC by KriiLunAus

2023-11-27 02:47 UTC, LILKRASH commented on src/partials/order.html
> +  <div class="women_in_green"></div>
елементи не можуть бути поза секцією,цю картинку може перенести куди завгодно при злитті секцій

2023-11-27 02:49 UTC, LILKRASH commented on src/css/order.css
> +  gap: 40px;
геп без флекса не працює

2023-11-27 02:52 UTC, LILKRASH commented on src/css/order.css
> +  padding: 80px 20px;
20 px і так є через базові стилі контейнеру

2023-11-28 08:29 UTC, LILKRASH requested changes

2023-11-28 08:29 UTC, LILKRASH commented on src/css/order.css
>      background-position: center;
отут ще топ додай після центру щоб її лице видно було

2023-11-28 08:29 UTC, LILKRASH commented on src/css/order.css
> +    padding-top: 50px;
ці падінги краще не задавати,візуально і так схоже

2023-11-28 08:29 UTC, LILKRASH commented on src/css/order.css
> +.all_wrap {
в цьому діві витри падінги просто додай собі клас container там за замовчуванням все є

2023-11-28 08:29 UTC, LILKRASH commented on src/css/order.css
> +  .all_wrap {
видали і клас контейнер постав він все відформатує

2023-11-28 08:59 UTC, KriiLunAus commented on src/css/order.css
> +    padding-top: 50px;
Воно схоже через падінги на хедері, а коли воно складеться, то має бути ок

2023-11-28 17:30 UTC, LILKRASH approved these changes

2023-11-28 17:30 UTC, merged