add section about us
LILKRASH/monsters-developers-project pull request #5
Opened 2023-11-24 12:34 UTC by Step004

2023-11-25 01:06 UTC, LILKRASH requested changes

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +.container {
падінги на контейнер я задав в базові стилі

2023-11-25 01:06 UTC, melnykartem3 commented on src/partials/about.html
> +<div class="section-about-us section">
чому дів а не секція?

2023-11-25 01:06 UTC, melnykartem3 commented on src/partials/about.html
> +            <!-- Desktop screen 1440-->
розташуй sources в порядку від мобілки до десктопу на 1440px

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +    padding-bottom: 40px;
повинен бути не падінг, а марджин

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +    text-align: left;
ця властивість не потрібна,він і так зліва стоїть

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +    padding-bottom: 20px;
знову задав падінг

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +.section-about-us-p-2 {
зайвий падінг

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +    line-height: 1.365;
line-height normal

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +    text-align: left;
зайва властивість

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +    position: relative;
position не потрібен

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +        padding-bottom: 40px;
не падінг а марджин

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +        line-height: 1.36;
line-height normal

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +        padding-left: 32px;
падінги на контейнер я задав в базові стилі

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +        padding-bottom: 80px;
падінг 150

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +        width: 436px;
краще макс ширину задати

2023-11-25 01:06 UTC, melnykartem3 commented on src/css/about.css
> +        width: 481px;
також макс ширина треба

2023-11-25 11:53 UTC, Step004 reviewed
Порядок фото в розділі pictures мусить бути в такому порядку, інакше не правильно реагує розмітка на фото

2023-11-25 17:39 UTC, LILKRASH requested changes

2023-11-25 17:39 UTC, LILKRASH commented on src/css/about.css
> +    background-position: right bottom 18px;
18 пікселів я думаю поки зайві

2023-11-25 17:39 UTC, LILKRASH commented on src/css/about.css
>          justify-content: center;
джастіфай не треба

2023-11-26 21:23 UTC, LILKRASH requested changes
3 екран переходу не 1220 а 1280 рх, і задай по половині падінгів як домовлялись

2023-11-27 01:42 UTC, LILKRASH requested changes
давай тільки ці пікселі приберемо і я прийму роботу,якщо що вже краще додамо,якщо буде погано виглядати

2023-11-27 01:42 UTC, LILKRASH commented on src/css/about.css
> +    background-position: right bottom -22px;
напевно все таки треба прибрати -22 , бо ніхто більше не ставить їх і виглядає норм

2023-11-27 01:42 UTC, LILKRASH commented on src/css/about.css
> +        background-position: right bottom -5px;
і тут прибери буль ласка

2023-11-27 01:42 UTC, LILKRASH commented on src/css/about.css
> -        background-position: right bottom 50px;
тут також прибери

2023-11-27 12:26 UTC, LILKRASH approved these changes

2023-11-27 12:27 UTC, merged