HEADER adds icons+ styles
LILKRASH/monsters-developers-project pull request #6
Opened 2023-11-24 22:09 UTC by Danilthedjun

2023-11-25 03:56 UTC, LILKRASH requested changes

2023-11-25 03:56 UTC, melnykartem3 commented on src/partials/header.html
>          <buttom class="header-burger" type="buttom">
**button а не buttom**.Коли пофіксиш налаштуй стилі кнопці і постав її в щоб вона була в хедері і власне в діві

2023-11-25 03:56 UTC, melnykartem3 commented on src/css/header.css
> +.header-logo {
додай зображенню клас і вимкни height:auto , дісплей блок можна також

2023-11-25 03:56 UTC, melnykartem3 commented on src/css/header.css
> +  padding: 7px;
padding: 8px

2023-11-25 03:56 UTC, melnykartem3 commented on src/css/header.css
> +  align-items: center;
не треба ставити центр, ти падінгами вирівняв

2023-11-25 03:56 UTC, melnykartem3 commented on src/css/header.css
> +  gap: 8px;
не бачу сенсу для геп

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +  background: transparent;
краще бг-колор написати

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    margin-right: 440px;
такий великий марджин бути не може, подумай як можна за допомогою флексів зробити цей відступ

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    margin-right: 20px;
шось не так

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    margin-right: 129px;
про марджин забудь. ****Флекс** тут бос**

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    line-height: 1.28em;
лайн хайт в ємах?

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    color: var(--main-color);
колір можна на задавати він і так наслідується

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +  .nav-item:hover,
транзішн

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    justify-content: center;
ти ж падінгами вирівняв

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    align-items: center;
така сама байда

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    gap: 10px;
а куди гепом відступать зібрався?)

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    color: var(--main-color);
можна колір не задавати

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    line-height: 1.4em;
і знову в ємах

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    margin-right: 20px;
відступ передивись

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +  address:focus {
транзішн

2023-11-25 03:56 UTC, LILKRASH commented on src/css/header.css
> +    margin-right: 289px;
**Флекс понад усе**

2023-11-25 16:53 UTC, LILKRASH requested changes
**Подивися щодо відступів верхніх і нижніх**

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
>  .page-header {
в мене до верху 24 пікселі, знизу на всіх пристроях різний падінг

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +  height: 39px;
краще в відсотках вказати

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +  display: inline;
дісплей по суті не потрібен

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +    padding-bottom: 80px;
відступ 110

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +    margin-right: 0;
марджин і так 0, просто прибрати можна

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +    gap: 440px;
геп не треба, а розташував правильно

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +    padding-bottom: 100px;
117 відступ

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +    gap: 129px;
геп зайвий

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +    line-height: 18px;
не вказуємо в пікселях лайн хейт

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +    line-height: 20px;
не в пікселях треба

2023-11-25 16:53 UTC, LILKRASH commented on src/css/header.css
> +    gap: 289px;
геп не треба

2023-11-25 20:32 UTC, LILKRASH requested changes
Коли будеш перероблювати зроби фетч оріджин бо я в базові випадковл 1220 а не 1280 зробив

2023-11-25 20:32 UTC, LILKRASH commented on src/css/header.css
>  @media screen and (min-width: 1220px) {
мін ширина1280 px,також від адресс до соц лінків 20 рх

2023-11-25 20:32 UTC, LILKRASH commented on src/css/header.css
> +  outline: 0;
транспарент а не 0

2023-11-25 20:32 UTC, LILKRASH commented on src/css/header.css
>  @media screen and (min-width: 768px) {
на планшеті відступ до кнопки 20 px а не 12

2023-11-25 20:32 UTC, LILKRASH commented on src/css/header.css
> +    padding-bottom: 104px;
102

2023-11-25 20:32 UTC, LILKRASH commented on src/css/header.css
> +  .header-phone:focus {
транзішн

2023-11-26 11:40 UTC, Danilthedjun commented on src/css/header.css
> +  .header-phone:focus {
він є

2023-11-26 12:14 UTC, LILKRASH requested changes
Все добре,зміни тільки час транзішн на іконках на 250 мс бо в тебе 1000

2023-11-26 19:40 UTC, LILKRASH approved these changes

2023-11-26 19:40 UTC, merged