hero-1
LILKRASH/monsters-developers-project pull request #7
Opened 2023-11-25 18:40 UTC by Daria2608

2023-11-25 22:53 UTC, LILKRASH requested changes

2023-11-25 22:53 UTC, melnykartem3 commented on src/css/hero.css
> +margin-left: 90px;
щоб поставити кнопку по центру треба марджин лефт і марджин райт авто

2023-11-25 22:53 UTC, melnykartem3 commented on src/css/hero.css
> +display: inline-flex;
просто флекс без інлайну

2023-11-25 22:53 UTC, melnykartem3 commented on src/css/hero.css
> +fill: #ECD979;
через вар задайте

2023-11-25 22:53 UTC, melnykartem3 commented on src/css/hero.css
> +height: 49px;
висота не потрібна

2023-11-25 22:53 UTC, melnykartem3 commented on src/css/hero.css
> +flex-shrink: 0;
зайва властивість

2023-11-25 22:53 UTC, melnykartem3 commented on src/css/hero.css
> +border: 1px solid var(--yellow, #ECD979);
краще вказати бордер колор

2023-11-25 22:53 UTC, melnykartem3 commented on src/css/hero.css
> +margin-left: 0;
не бачу сенсу цієї властивості

2023-11-25 22:53 UTC, melnykartem3 commented on src/css/hero.css
> +padding: 14px 39px;
падінги вже задані на мобілку таблет унаслідував

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +.hero-link {
кнопка повинна бути відцентрована марджинами по середині діва якому потрібно зменшити ширину

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +fill: #ECD979;
задайте через вар

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +color: rgba(252, 249, 249, 0.40);
через вар

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +.hero-text {
параграф повинен бути відштовхнутим від правого краю та вирівняний як по макету відносно заголовку

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +.icon-hero {
елемент повинен бути зпозиційованим

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +.hero-container {
не зрозумів для чого задали

2023-11-25 22:53 UTC, LILKRASH commented on src/partials/hero.html
> +      <svg class="icon-hero" width="52" height="51">
елемент повинен бути винесеним з потоку та зпозиційованим

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +.hero-container-decor {
елемент не відображається, передивіться як робили в попередній роботі

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +.hero-title-button {
навіщо ці марджини?

2023-11-25 22:53 UTC, LILKRASH commented on src/css/hero.css
> +margin-left: 181px;
огортайте в діви і так робіть відступи

2023-11-25 22:58 UTC, LILKRASH commented
зірку та півкруг потрібно позиціювати а параграф біля зірки ні

2023-11-28 07:25 UTC, LILKRASH requested changes
Я думаю краще додати дів тільки на кнопку і зробити їй на всіх пристроях відступи віж країв саме падінгами.також потрібно на екрані 1280,який ви повинні змінити в медіаправилі з 1220,змінити ширину заголовку.і якщо ви помітили то на десктопних екранах зірка та параграф ідуть вище заголовку

2023-11-28 07:25 UTC, LILKRASH commented on src/css/hero.css
>  @media screen and (min-width: 1220px) {
повинно бути 1280px

2023-11-28 17:48 UTC, LILKRASH reviewed
Переробіть за рекомаендаціями які я надав

2023-11-29 01:27 UTC, LILKRASH approved these changes

2023-11-29 01:28 UTC, melnykartem3 approved these changes

2023-11-29 01:28 UTC, merged